---

- name: install openssl
  apt:
    name: openssl
    state: present

- name: create /srv/nginx/certs
  file:
    path: /srv/nginx/certs
    state: directory

- name: create self-signed certificate
  shell: |
    openssl req -new -nodes -x509 -extensions v3_ca \
      -subj "/C=FR/ST=IdF/L=Paris/O=IT/CN={{ ansible_host }}" \
      -days 3650 \
      -keyout /srv/nginx/certs/{{ ansible_host }}.key \
      -out /srv/nginx/certs/{{ ansible_host }}.crt
  args:
    creates: "/srv/nginx/certs/{{ ansible_host }}.crt"
