---

ipfs_api_fqdn: "{{ ansible_host }}"

ipfs_version: "v0.11.0"

ipfs_nginx_proxy_vhost_dir: ""

ipfs_srv_dir: "/srv/ipfs"
ipfs_staging_dir: "/opt/ipfs/staging"
ipfs_data_dir: "/opt/ipfs/data"

ipfs_config:
  API:
    HTTPHeaders:
      Access-Control-Allow-Origin:
        - "https://{{ ipfs_api_fqdn }}"
      Access-Control-Allow-Methods:
        - "PUT"
        - "POST"
