---

- name: create EFK directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /srv/efk

- name: create EFK mounted directories
  file:
    path: "{{ item }}"
    state: directory
    mode: u=rwx,g=rwx,o=rx
  loop:
    - /data/fluent-bit/config
    - /data/elasticsearch/data

- name: copy fluent-bit.conf
  copy:
    src: fluent-bit.conf
    dest: /data/fluent-bit/config/fluent-bit.conf
  notify: restart fluent-bit

- name: template EFK docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /srv/efk/docker-compose.yml

- name: start EFK
  docker_compose:
    project_src: /srv/efk
