all:
  hosts:
    amenda:
      ansible_host: "ssh.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ (base_hostname == 'amenda.fr.test') | ternary('/vagrant/.vagrant/machines/amenda/virtualbox/private_key', '/vagrant/key/amenda.fr') }}"
      ansible_ssh_user: root
      ansible_become: yes
    forum:
      ansible_host: "forum.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ (base_hostname == 'amenda.fr.test') | ternary('/vagrant/.vagrant/machines/amenda/virtualbox/private_key', '/vagrant/key/amenda.fr') }}"
      ansible_ssh_user: root
      ansible_become: yes
    monitoring:
      ansible_host: "monitoring.infra.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ (base_hostname == 'amenda.fr.test') | ternary('/vagrant/.vagrant/machines/amenda/virtualbox/private_key', '/vagrant/key/amenda.fr') }}"
      ansible_ssh_user: root
      ansible_become: yes
    metrics:
      ansible_host: "metrics.infra.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ (base_hostname == 'amenda.fr.test') | ternary('/vagrant/.vagrant/machines/amenda/virtualbox/private_key', '/vagrant/key/amenda.fr') }}"
      ansible_ssh_user: root
      ansible_become: yes
    logs:
      ansible_host: "logs.infra.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ (base_hostname == 'amenda.fr.test') | ternary('/vagrant/.vagrant/machines/amenda/virtualbox/private_key', '/vagrant/key/amenda.fr') }}"
      ansible_ssh_user: root
      ansible_become: yes
    analytics:
      ansible_host: "analytics.infra.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ (base_hostname == 'amenda.fr.test') | ternary('/vagrant/.vagrant/machines/amenda/virtualbox/private_key', '/vagrant/key/amenda.fr') }}"
      ansible_ssh_user: root
      ansible_become: yes

infra:
  hosts:
    monitoring:
    metrics:
    logs:
    analytics:

server:
  hosts:
    amenda:

webserver:
  hosts:
    amenda:

ssl:
  hosts:
    forum:
    monitoring:
    metrics:
    logs:
    analytics:
