all:
  hosts:
    govlab:
      ansible_host: "ssh.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ vault_govlab_io_ssh_key | default(default_govlab_io_ssh_key) }}"
      ansible_ssh_user: root
      ansible_become: yes
    community:
      ansible_host: "community.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ vault_community_govlab_io_ssh_key | default(default_community_govlab_io_ssh_key) }}"
      ansible_ssh_user: root
      ansible_become: yes
    monitoring:
      ansible_host: "monitoring.infra.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ vault_monitoring_infra_govlab_io_ssh_key | default(default_monitoring_infra_govlab_io_ssh_key) }}"
      ansible_ssh_user: root
      ansible_become: yes
    metrics:
      ansible_host: "metrics.infra.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ vault_metrics_infra_govlab_io_ssh_key | default(default_metrics_infra_govlab_io_ssh_key) }}"
      ansible_ssh_user: root
      ansible_become: yes
    logs:
      ansible_host: "logs.infra.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ vault_logs_infra_govlab_io_ssh_key | default(default_logs_infra_govlab_io_ssh_key) }}"
      ansible_ssh_user: root
      ansible_become: yes
    analytics:
      ansible_host: "analytics.infra.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ vault_analytics_infra_govlab_io_ssh_key | default(default_analytics_infra_govlab_io_ssh_key) }}"
      ansible_ssh_user: root
      ansible_become: yes
    cloud:
      ansible_host: "cloud.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ vault_cloud_govlab_io_ssh_key | default(default_cloud_govlab_io_ssh_key) }}"
      ansible_ssh_user: root
      ansible_become: yes

vouch:
  hosts:
    monitoring:
    metrics:
    logs:
    analytics:

server:
  hosts:
    govlab:

webserver:
  hosts:
    govlab:

ssl:
  hosts:
    community:
    # monitoring:
    # metrics:
    # logs:
    analytics:
    cloud:
