all:
  hosts:
    govlab:
      ansible_host: "ssh.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ vault_govlab_io_ssh_key | default(default_govlab_io_ssh_key) }}"
      ansible_ssh_user: root
      ansible_become: yes
    community:
      ansible_host: "ssh.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ vault_community_govlab_io_ssh_key | default(default_community_govlab_io_ssh_key) }}"
      ansible_ssh_user: root
      ansible_become: yes
    analytics:
      ansible_host: "ssh.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ vault_analytics_infra_govlab_io_ssh_key | default(default_analytics_infra_govlab_io_ssh_key) }}"
      ansible_ssh_user: root
      ansible_become: yes
    cloud:
      ansible_host: "ssh.{{ base_hostname }}"
      ansible_ssh_private_key_file: "{{ vault_cloud_govlab_io_ssh_key | default(default_cloud_govlab_io_ssh_key) }}"
      ansible_ssh_user: root
      ansible_become: yes

vouch:
  hosts:
    analytics:
      vouch_fqdn: "analytics.infra.{{ base_hostname }}"

server:
  hosts:
    govlab:

webserver:
  hosts:
    govlab:

ssl:
  hosts:
    community:
    analytics:
    cloud:
